FROM python:3.11-slim

WORKDIR /app
ENV COQUI_TOS_AGREED=1
RUN apt-get update && apt-get install -y --no-install-recommends \
    ffmpeg \
    libcairo2 \
    libcairo2-dev \
    pkg-config \
    gcc \
    g++ \
    git \
    && rm -rf /var/lib/apt/lists/*

COPY requirements-tts.txt ./

RUN pip install --upgrade pip

RUN pip install torch==2.4.1 torchaudio==2.4.1 --index-url https://download.pytorch.org/whl/cpu
RUN pip install --no-cache-dir -r requirements-tts.txt

COPY back/ ./back/
COPY voix.json ./

EXPOSE 8001

CMD ["uvicorn", "back.TTs.tts_api:app", "--host", "0.0.0.0", "--port", "8001"]